
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthcare-dev
  labels:
    app: patient-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service

  template:
    metadata:
      labels:
        app: patient-service

    spec:
      containers:
        - name: patient-service
          image: ghcr.io/githostan/healthcare-platform/patient-service:sha-a796ade               
          imagePullPolicy: IfNotPresent                                           
          ports:
            - containerPort: 8000                       

          env:
            - name: PATIENT_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: patient-service-secret
                  key: PATIENT_SERVICE_API_KEY
            - name: ENVIRONMENT
              value: "dev"
            - name: ENABLE_SEED_DATA
              value: "true"
            - name: LOG_LEVEL
              value: "INFO"


          readinessProbe:                                            
            httpGet:
              path: /readyz                                         
              port: 8000
            initialDelaySeconds: 5                                  
            periodSeconds: 10                                       

          livenessProbe:                                            
            httpGet:
              path: /healthz                                       
              port: 8000
            initialDelaySeconds: 10       
            periodSeconds: 15             
            # timeoutSeconds: 60
            # failureThreshold: 1
          
          resources:
            requests:
              cpu: "25m"                                           
              memory: "64Mi"                                       
            limits:
              cpu: "200m"        
              memory: "128Mi"                                       
                                                   



          